#!/bin/bash
#
# BIND
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=service/$(basename $0)
NAME=${INSTANCE_PREFIX}$(basename $0)

OPTIONS=""
OPTIONS="${OPTIONS} --volumes-from ${NAME}.volumes"
OPTIONS="${OPTIONS} --volumes-from ${NAME}.volumes"

VOLUEMS="-v /var/named"

case $MODE in
name)
    echo $NAME
    ;;
run)
    docker create ${VOLUMES} --name ${NAME}.voluems busybox

    docker run $OPTIONS \
        --volumes-from ${NAME}.volumes
        --privileged \
        --name $NAME \
        --hostname $NAME \
        -d $IMAGE
    ;;
stop)
    docker stop -t 2 $NAME
    docker rm $NAME
    ;;
esac

