#!/bin/bash 
#
# DNS-SERVER
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/dnsmasq
IMAGE=service/dnsmasq
NAME=${INSTANCE_PREFIX}dns
OPTIONS=${DNS_INSTANCE_OPTIONS}

case $MODE in
name)
    echo $NAME
    ;;
run)
    # DNSMASQ
    echo "STARTING ".$NAME
    docker run -d $OPTIONS \
        -v ${CONFIG_DIR}/${NAME}:/var/dnsmasq \
        --privileged \
        --name $NAME \
        --hostname $NAME \
        $IMAGE && {
            $0 up
        }
    ;;
up)
    IP=$(
    docker \
        inspect \
        -f '{{.NetworkSettings.IPAddress}}' $NAME)
    echo nameserver $IP > /etc/resolv.conf
    echo nameserver 8.8.8.8 >> /etc/resolv.conf
    echo nameserver 8.8.4.4 >> /etc/resolv.conf
    nd-ctrl dns status
    ;;
stop)
    docker stop -t 2 $NAME
    docker rm $NAME
    ;;
esac

