#!/bin/bash
#
# NGINX-GW
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=service/nginx
NAME=${INSTANCE_PREFIX}$(basename $0)
OPTIONS=
OPTIONS="${OPTIONS} -p 80:80 -p 443:443"
OPTIONS="${OPTIONS} --dns $(nd-ip dns)"
OPTIONS="${OPTIONS} --name ${NAME}"
OPTIONS="${OPTIONS} --hostname ${NAME}"
OPTIONS="${OPTIONS} --volumes-from ${NAME}.volumes"
OPTIONS="${OPTIONS} -v /var/cache"

VOLUMES="${VOLUMES} -v ${DATA}:/etc/nginx"
#VOLUMES="${VOLUMES} -v ${DATA}/var/cache:/var/cache/nginx"

case $MODE in
run)
    docker run --name ${NAME}.volumes $VOLUMES busybox 2> /dev/null || echo 'data exists?'
    exit 200
    ;;
name)
    echo $NAME
    ;;
image)
    echo $IMAGE
    ;;
options)
    echo $OPTIONS
    ;;
*)
    exit 200
    ;;
esac
