#!/bin/bash
#
# Nora開発用サーバ
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=nora/dev
NAME=${INSTANCE_PREFIX}$(basename $0)
OPTIONS=
OPTIONS="${OPTIONS} --dns $(nd-ip dns)"
OPTIONS="${OPTIONS} --name ${NAME}"
OPTIONS="${OPTIONS} --hostname ${NAME}"
OPTIONS="${OPTIONS} --volumes-from ${NAME}.volumes"
OPTIONS="${OPTIONS} -p 7080:80"
OPTIONS="${OPTIONS} -p 7081:8080"
OPTIONS="${OPTIONS} -p 7222:22"

VOLUMES=
VOLUMES="${VOLUMES} -v /opt/php/etc/php-fpm"
VOLUMES="${VOLUMES} -v /etc/nginx"
VOLUMES="${VOLUMES} -v /home"
VOLUMES="${VOLUMES} -v /var/lib/nginx/proxy"
VOLUMES="${VOLUMES} -v /startup/local"

case $MODE in
name)
    echo $NAME
    ;;
image)
    echo $IMAGE
    ;;
options)
    echo $OPTIONS
    ;;
run)
    docker create ${VOLUMES} --name ${NAME}.volumes busybox 
    exit 200
    ;;
*)
    exit 200
    ;;
esac
