#!/bin/bash
#
# Openldap
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=service/openldap
NAME=${INSTANCE_PREFIX}$(basename $0)

mkdir -p ${CONFIG_DIR}/${NAME}
touch ${CONFIG_DIR}/${NAME}/slapd.conf

OPTIONS=
OPTIONS="${OPTIONS} -v ${CONFIG_DIR}/${NAME}/slapd.conf:/etc/openldap/slapd.conf"
OPTIONS="${OPTIONS} -v ${CONFIG_DIR}/${NAME}/startup:/startup/local"
OPTIONS="${OPTIONS} -v ${CONFIG_DIR}/${NAME}/slapd.d:/etc/openldap/slapd.d"
OPTIONS="${OPTIONS} -v ${CONFIG_DIR}/${NAME}/openldap-data:/var/lib/openldap/openldap-data"
OPTIONS="${OPTIONS} -v /etc/skel:/etc/skel"
OPTIONS="${OPTIONS} --dns $(nd-ip dns)"
OPTIONS="${OPTIONS} --name ${NAME}"
OPTIONS="${OPTIONS} --hostname ${NAME}"
#OPTIONS="${OPTIONS} -p 389:389"                                      # Ldapを公開する

case $MODE in
name)
    echo $NAME
    ;;
options)
    echo $OPTIONS
    ;;
image)
    echo $IMAGE
    ;;
*)
    exit 200
esac
