#!/bin/bash
#
# Openldap
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=service/openldap
NAME=${INSTANCE_PREFIX}$(basename $0)

mkdir -p ${CONFIG_DIR}/${NAME}
touch ${CONFIG_DIR}/${NAME}/slapd.conf

OPTIONS=
OPTIONS="${OPTIONS} --dns $(nd-ip dns)"
OPTIONS="${OPTIONS} --name ${NAME}"
OPTIONS="${OPTIONS} --hostname ${NAME}"
OPTIONS="${OPTIONS} --volumes-from ${NAME}.volumes"
#OPTIONS="${OPTIONS} -p 389:389"                                      # Ldapを公開する

VOLUMES=
VOLUMES="${VOLUMES} -v /etc/openldap/slapd.conf"
VOLUMES="${VOLUMES} -v /startup/local"
VOLUMES="${VOLUMES} -v /etc/openldap/slapd.d"
VOLUMES="${VOLUMES} -v /var/lib/openldap/openldap-data"
case $MODE in

name)
    echo $NAME
    ;;
options)
    echo $OPTIONS
    ;;
image)
    echo $IMAGE
    ;;
run)
    docker creat ${VOLUMES} --name ${NAME}.volumes busybox
    exit 200
    ;;
*)
    exit 200
esac
