#!/bin/bash
#
# POSTFIX-GW
#
source ./config/vars

MODE=$1
DATA=${CONFIG_DIR}/$(basename $0)
IMAGE=service/postfix
NAME=${INSTANCE_PREFIX}$(basename $0)

OPTIONS=
OPTIONS="$OPTIONS --volumes-from ${NAME}.volumes"
OPTIONS="$OPTIONS -p 25:25 "
OPTIONS="$OPTIONS --dns $(nd-ip dns) "
OPTIONS="$OPTIONS --name ${NAME}"
OPTIONS="$OPTIONS --hostname ${NAME}"

case $MODE in
name)
    echo $NAME
    ;;
image)
    echo $IMAGE
    ;;
options)
    echo $OPTIONS
    ;;
run)
    docker create --name ${NAME}.volumes  -v /etc/postfix -v /var/spool/postfix busybox
    exit 200
    ;;
*)
    exit 200
    ;;
esac

